#!/usr/bin/env bash

# Simulation script to verify operation of the block memory

set -o errexit  # -e
set -o nounset  # -u
set -o pipefail
IFS=$' \n\t'

# Verify that the simulation script is being run from the /sim directory
# otherwise exit.
full_pwd="$(readlink -f "$(pwd)")"
if [[ "$(basename "$full_pwd")" == "sim" ]]; then
    root_dir="$(dirname "$full_pwd")"
else
    echo "ERROR: Simulation script must be run from the /sim directory."
    exit 1
fi

# Names needed for working with Xilinx block memory IP
memory_ip="memory_block"
memory_model="blk_mem_gen_v8_3.v"

# Set up commonly used variables and locations
scripts_dir="$root_dir/scripts"
build_dir="$root_dir/build"
roms_dir="$root_dir/roms"
memory_dir="$build_dir/$memory_ip"
sim_dir="$root_dir/sim"
lib_dir="$sim_dir/proc_lib"

# Export important variables so the EDA tools can be found
export QUESTA_PATH="/opt/Altera/intelFPGA_pro/17.0/modelsim_ase/linux"
export XILINX_VIVADO="/opt/Xilinx/Vivado/2017.1"

sim_file="memory_sim.tcl"
if [[ -f "$sim_file" ]]; then
    vsim -c -do "$sim_file"
fi
