#!/usr/bin/env bash

# High level simulation script for the MOS 6502 processor
#
# To run a simulation, run this script and provide the desired addressing mode
# to be simulated:
#
# $ ./proc_sim absolute
#
# This will run the 'proc_tb.v' from /testbench with the absolute.asm from
# /roms. A number of interim steps are currently required (e.g., building a
# block memory, assembling source code into .mif files). Those are no longer
# necessary as the simulation script is now sophisticated enough to automate all
# of that, rather than relying on the user to do it correctly.

set -o errexit
set -o nounset
set -o pipefail
IFS='$ \n\t'

# Simulation script must be run from the /sim directory
#full_pwd="$(greadlink -f "$(pwd)")"
#if [[ "$(basename "$full_pwd")" == "sim" ]]; then
#    # Location to the project root directory
#    root_dir="$(dirname "$full_pwd")"
#else
#    echo "ERROR: Simulation script must be run from the /sim directory."
#    exit 1
#fi

root_dir="../"

# Names needed for working with Xilinx block memory IP
memory_ip="memory_block"
memory_model="blk_mem_gen_v8_3.v"

# Some commonly used directories
scripts_dir="$root_dir/scripts"
build_dir="$root_dir/build"
memory_dir="$build_dir/$memory_ip"

# Temporary directories
tmp_dir="/tmp"
sim_dir="$tmp_dir/proc_sim"

# Make these environment variables  available to the Tcl interpreter
export QUESTA_PATH="/opt/Altera/intelFPGA_pro/17.0/modelsim_ase/linux"
export XILINX_VIVADO="/opt/Xilinx/Vivado/2017.1"

# Supported addressing modes and test cases - should correspond to the names of
# testbenches, ROMs, and Tcl scripts to run for each/
supported=( "absolute" "absolute-x" "absolute-y" )

# Error out if requested test case invalid or not provided
if [[ "$#" -eq 0 ]]; then
    echo "Usage: proc_sim [TEST CASE]"
    exit 1
else
    mode="${1:-}"
    found=0
    for available in "${supported[@]}"
    do
        if [[ "$mode" == "$available" ]]; then
            echo "INFO: Simulating $mode addressing mode."
            found=1
            break
        fi
    done
    if (( ! "$found" )); then
        echo "ERROR: $mode is not a supported addressing mode or test case."
        exit 1
    fi
fi

# Delete any existing directory in /tmp - check to make sure that user has
# permissions for this and error out if not (making different directories within
# /tmp/proc_sim allows multiple simulations to be carried out in parallel
if [[ ! -w "$tmp_dir" || ! -r "$tmp_dir" ]]; then
    echo "ERROR: Directory $tmp_dir not readable or writable by current user."
    exit 1
elif [[ -d "$sim_dir" ]]; then
    rm -rf "$sim_dir"
fi
mkdir -pv "$sim_dir/$mode"

# If no block memory has been built yet, create one.  Otherwise, use the existing
# one.  In both cases, build a .mif to use for simulation.
if [[ ! -f "$memory_dir/simulation/$memory_model" ]]; then
    echo "INFO: No behavioral model for the Block Memory Generator Core found."
    # Delete any remnants of the memory model if they exist
    if [[ -d "$memory_dir" ]]; then
        rm -rf "$memory_dir"
    fi






# If it hasn't been built yet, generate a .coe file from the .asm file for this
# mode and then build a memory block using that .coe file

# Generate a new .mif file for use in simulating the proc and block memory

# Build all simulation files in /tmp/proc_sim/$mode


# case "$mode" in

#     "absolute")
#         echo "Testing absolute addressing mode."

#         # Require a memory_block simulation model to exist before continuing
#         memory_dir="../build/memory_block"
#         if [[ ! -f "$memory_dir/sim/memory_block.v" ]]; then
#             echo "ERROR: No block RAM simulation model found."
#             exit 1
#         fi

#         # Creating simulation directory
#         sim_dir=./"$mode"_lib/
#         echo "INFO: Creating simulation directory $(pwd -P)/$sim_dir"
#         if [[ -d "$sim_dir" ]]; then
#             rm -rf "$sim_dir"
#         fi
#         mkdir -p "$sim_dir"

#         vsim -c -do "$mode"_sim.tcl
#         ;;
#     "absolute X")
#         echo "Testing absolute indexed X addressing mode."
#         ;;
#     "absolute Y")
#         echo "Testing absolute indexed Y addressing mode."
#         ;;
#     *)
#         echo "$mode is not a valid addressing mode"
#         ;;
# esac


# #
# # # Look for the appropriate simulation .asm file to use
# #
# # # Compile the .asm file into a .mif
# #
# # # Move the .mif into the /sim directory
# #
